export const heights = [
  { label: '4 Ft 5 In', value: '4 Ft 5 In' },
  { label: '4 Ft 6 In', value: '4 Ft 6 In' },
  { label: '4 Ft 7 In', value: '4 Ft 7 In' },
  { label: '4 Ft 8 In', value: '4 Ft 8 In' },
  { label: '4 Ft 9 In', value: '4 Ft 9 In' },
  { label: '5 Ft 0 In', value: '5 Ft 0 In' },
  { label: '5 Ft 1 In', value: '5 Ft 1 In' },
  { label: '5 Ft 2 In', value: '5 Ft 2 In' },
  { label: '5 Ft 3 In', value: '5 Ft 3 In' },
  { label: '5 Ft 4 In', value: '5 Ft 4 In' },
  { label: '5 Ft 5 In', value: '5 Ft 5 In' },
  { label: '5 Ft 6 In', value: '5 Ft 6 In' },
  { label: '5 Ft 7 In', value: '5 Ft 7 In' },
  { label: '5 Ft 8 In', value: '5 Ft 8 In' },
  { label: '5 Ft 9 In', value: '5 Ft 9 In' },
  { label: '6 Ft 0 In', value: '6 Ft 0 In' },
  { label: '6 Ft 1 In', value: '6 Ft 1 In' },
  { label: '6 Ft 2 In', value: '6 Ft 2 In' },
  { label: '6 Ft 3 In', value: '6 Ft 3 In' },
  { label: '6 Ft 4 In', value: '6 Ft 4 In' },
  { label: '6 Ft 5 In', value: '6 Ft 5 In' },
  { label: '6 Ft 6 In', value: '6 Ft 6 In' },
  { label: '6 Ft 7 In', value: '6 Ft 7 In' },
  { label: '6 Ft 8 In', value: '6 Ft 8 In' },
  { label: '6 Ft 9 In', value: '6 Ft 9 In' },
  { label: '7 Ft 0 In', value: '7 Ft 0 In' },
];

export const weight = [
  { label: '40 kg', value: '40 kg' },
  { label: '41 kg', value: '41 kg' },
  { label: '42 kg', value: '42 kg' },
  { label: '43 kg', value: '43 kg' },
  { label: '44 kg', value: '44 kg' },
  { label: '45 kg', value: '45 kg' },
  { label: '46 kg', value: '46 kg' },
  { label: '47 kg', value: '47 kg' },
  { label: '48 kg', value: '48 kg' },
  { label: '49 kg', value: '49 kg' },
  { label: '50 kg', value: '50 kg' },
  { label: '51 kg', value: '51 kg' },
  { label: '52 kg', value: '52 kg' },
  { label: '53 kg', value: '53 kg' },
  { label: '54 kg', value: '54 kg' },
  { label: '55 kg', value: '55 kg' },
  { label: '56 kg', value: '56 kg' },
  { label: '57 kg', value: '57 kg' },
  { label: '58 kg', value: '58 kg' },
  { label: '59 kg', value: '59 kg' },
  { label: '60 kg', value: '60 kg' },
  { label: '61 kg', value: '61 kg' },
  { label: '62 kg', value: '62 kg' },
  { label: '63 kg', value: '63 kg' },
  { label: '64 kg', value: '64 kg' },
  { label: '65 kg', value: '65 kg' },
  { label: '66 kg', value: '66 kg' },
  { label: '67 kg', value: '67 kg' },
  { label: '68 kg', value: '68 kg' },
  { label: '69 kg', value: '69 kg' },
  { label: '70 kg', value: '70 kg' },
  { label: '71 kg', value: '71 kg' },
  { label: '72 kg', value: '72 kg' },
  { label: '73 kg', value: '73 kg' },
  { label: '74 kg', value: '74 kg' },
  { label: '75 kg', value: '75 kg' },
  { label: '76 kg', value: '76 kg' },
  { label: '77 kg', value: '77 kg' },
  { label: '78 kg', value: '78 kg' },
  { label: '79 kg', value: '79 kg' },
  { label: '80 kg', value: '80 kg' },
  { label: '81 kg', value: '81 kg' },
  { label: '82 kg', value: '82 kg' },
  { label: '83 kg', value: '83 kg' },
  { label: '84 kg', value: '84 kg' },
  { label: '85 kg', value: '85 kg' },
  { label: '86 kg', value: '86 kg' },
  { label: '87 kg', value: '87 kg' },
  { label: '88 kg', value: '88 kg' },
  { label: '89 kg', value: '89 kg' },
  { label: '90 kg', value: '90 kg' },
  { label: '91 kg', value: '91 kg' },
  { label: '92 kg', value: '92 kg' },
  { label: '93 kg', value: '93 kg' },
  { label: '94 kg', value: '94 kg' },
  { label: '95 kg', value: '95 kg' },
  { label: '96 kg', value: '96 kg' },
  { label: '97 kg', value: '97 kg' },
  { label: '98 kg', value: '98 kg' },
  { label: '99 kg', value: '99 kg' },
  { label: '100 kg', value: '100 kg' },
  { label: '101 kg', value: '101 kg' },
  { label: '102 kg', value: '102 kg' },
  { label: '103 kg', value: '103 kg' },
  { label: '104 kg', value: '104 kg' },
  { label: '105 kg', value: '105 kg' },
  { label: '106 kg', value: '106 kg' },
  { label: '107 kg', value: '107 kg' },
  { label: '108 kg', value: '108 kg' },
  { label: '109 kg', value: '109 kg' },
  { label: '110 kg', value: '110 kg' },
  { label: '111 kg', value: '111 kg' },
  { label: '112 kg', value: '112 kg' },
  { label: '113 kg', value: '113 kg' },
  { label: '114 kg', value: '114 kg' },
  { label: '115 kg', value: '115 kg' },
  { label: '116 kg', value: '116 kg' },
  { label: '117 kg', value: '117 kg' },
  { label: '118 kg', value: '118 kg' },
  { label: '119 kg', value: '119 kg' },
  { label: '120 kg', value: '120 kg' },
  { label: '121 kg', value: '121 kg' },
  { label: '122 kg', value: '122 kg' },
  { label: '123 kg', value: '123 kg' },
  { label: '124 kg', value: '124 kg' },
  { label: '125 kg', value: '125 kg' },
  { label: '126 kg', value: '126 kg' },
  { label: '127 kg', value: '127 kg' },
  { label: '128 kg', value: '128 kg' },
  { label: '129 kg', value: '129 kg' },
  { label: '130 kg', value: '130 kg' },
  { label: '131 kg', value: '131 kg' },
  { label: '132 kg', value: '132 kg' },
  { label: '133 kg', value: '133 kg' },
  { label: '134 kg', value: '134 kg' },
  { label: '135 kg', value: '135 kg' },
  { label: '136 kg', value: '136 kg' },
  { label: '137 kg', value: '137 kg' },
  { label: '138 kg', value: '138 kg' },
  { label: '139 kg', value: '139 kg' },
  { label: '140 kg', value: '140 kg' },
];

export const age = [
  { label: '18', value: '18' },
  { label: '19', value: '19' },
  { label: '20', value: '20' },
  { label: '21', value: '21' },
  { label: '22', value: '22' },
  { label: '23', value: '23' },
  { label: '24', value: '24' },
  { label: '25', value: '25' },
  { label: '26', value: '26' },
  { label: '27', value: '27' },
  { label: '28', value: '28' },
  { label: '29', value: '29' },
  { label: '30', value: '30' },
  { label: '31', value: '31' },
  { label: '32', value: '32' },
  { label: '33', value: '33' },
  { label: '34', value: '34' },
  { label: '35', value: '35' },
  { label: '36', value: '36' },
  { label: '37', value: '37' },
  { label: '38', value: '38' },
  { label: '39', value: '39' },
  { label: '40', value: '40' },
];

export const bodyTypes = [
  { label: 'Slim', value: 'Slim' },
  { label: 'Athletic', value: 'Athletic' },
  { label: 'Average', value: 'Average' },
  { label: 'Heavy', value: 'Heavy' },
];

export const physicalStatus = [
  { label: 'Normal', value: 'Normal' },
  { label: 'Physically challenged', value: 'Physically challenged' },
];

export const maritalStatus = [
  { label: 'Never married', value: 'Never married' },
  { label: 'Widowed', value: 'Widowed' },
  { label: 'Divorced', value: 'Divorced' },
  { label: 'Awaiting divorce', value: 'Awaiting divorce' },
];

export const eatingHabits = [
  { label: 'Vegetarian', value: 'Vegetarian' },
  { label: 'Non vegetarian', value: 'Non vegetarian' },
];

export const drinkingHabits = [
  { label: 'Never', value: 'Never' },
  { label: 'Ocassionally', value: 'Ocassionally' },
  { label: 'Regulary', value: 'Regulary' },
];

export const smokingHabits = [
  { label: 'Never', value: 'Never' },
  { label: 'Ocassionally', value: 'Ocassionally' },
  { label: 'Regulary', value: 'Regulary' },
];

export const religions = [
  { label: 'Hinduism', value: 'Hinduism' },
  { label: 'Islam', value: 'Islam' },
  { label: 'Christianity', value: 'Christianity' },
  { label: 'Sikhism', value: 'Sikhism' },
  { label: 'Buddhism', value: 'Buddhism' },
  { label: 'Jainism', value: 'Jainism' },
  { label: 'Zoroastrianism', value: 'Zoroastrianism' },
  { label: 'Baháí Faith', value: 'Baháí Faith' },
  { label: 'Tribal Religions', value: 'Tribal Religions' },
  { label: 'Judaism', value: 'Judaism' },
];

export const ethnicities = [
  { label: 'Bengali', value: 'Bengali' },
  { label: 'Punjabi', value: 'Punjabi' },
  { label: 'Gujarati', value: 'Gujarati' },
  { label: 'Marathi', value: 'Marathi' },
  { label: 'Tamil', value: 'Tamil' },
  { label: 'Telugu', value: 'Telugu' },
  { label: 'Kannada', value: 'Kannada' },
  { label: 'Odia', value: 'Odia' },
  { label: 'Assamese', value: 'Assamese' },
  { label: 'Kashmiri', value: 'Kashmiri' },
];

export const caste = [
  { label: 'Brahmins', value: 'Brahmins' },
  { label: 'Kshatriyas', value: 'Kshatriyas' },
  { label: 'Vaishyas', value: 'Vaishyas' },
  { label: 'Shudras', value: 'Shudras' },
  { label: 'Dalits', value: 'Dalits' },
];

export const educationalQualifications = [
  { label: 'High School Diploma', value: 'High School Diploma' },
  { label: "Bachelor's Degree", value: "Bachelor's Degree" },
  { label: "Master's Degree", value: "Master's Degree" },
  { label: 'Doctorate (Ph.D.)', value: 'Doctorate (Ph.D.)' },
  { label: "Associate's Degree", value: "Associate's Degree" },
  { label: 'Professional Certification', value: 'Professional Certification' },
  { label: 'Vocational Training', value: 'Vocational Training' },
  { label: 'Postgraduate Diploma', value: 'Postgraduate Diploma' },
  { label: 'Certificate Program', value: 'Certificate Program' },
  { label: 'Technical Degree', value: 'Technical Degree' },
];

export const employeeSectors = [
  { label: 'Information Technology', value: 'Information Technology' },
  { label: 'Healthcare', value: 'Healthcare' },
  { label: 'Finance', value: 'Finance' },
  { label: 'Education', value: 'Education' },
  { label: 'Manufacturing', value: 'Manufacturing' },
];

export const occupations = [
  { label: 'Teacher', value: 'Teacher' },
  { label: 'Doctor', value: 'Doctor' },
  { label: 'Engineer', value: 'Engineer' },
  { label: 'Accountant', value: 'Accountant' },
  { label: 'Lawyer', value: 'Lawyer' },
  { label: 'Chef', value: 'Chef' },
  { label: 'Artist', value: 'Artist' },
  { label: 'Police Officer', value: 'Police Officer' },
  { label: 'Journalist', value: 'Journalist' },
  { label: 'Salesperson', value: 'Salesperson' },
  { label: 'Electrician', value: 'Electrician' },
  { label: 'Plumber', value: 'Plumber' },
];

export const annualIncomes = [
  { label: 'Less than $20,000', value: 'Less than $20,000' },
  { label: '$20,000 - $40,000', value: '$20,000 - $40,000' },
  { label: '$40,000 - $60,000', value: '$40,000 - $60,000' },
  { label: '$60,000 - $80,000', value: '$60,000 - $80,000' },
  { label: '$80,000 - $100,000', value: '$80,000 - $100,000' },
  { label: 'More than $100,000', value: 'More than $100,000' },
];

export const countries = [
  { label: 'United States', value: 'United States' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'Canada', value: 'Canada' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Germany', value: 'Germany' },
  { label: 'France', value: 'France' },
  { label: 'Japan', value: 'Japan' },
  { label: 'China', value: 'China' },
  { label: 'India', value: 'India' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Russia', value: 'Russia' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Italy', value: 'Italy' },
];

export const cities = [
  { label: 'New York', value: 'New York' },
  { label: 'London', value: 'London' },
  { label: 'Toronto', value: 'Toronto' },
  { label: 'Sydney', value: 'Sydney' },
  { label: 'Berlin', value: 'Berlin' },
  { label: 'Paris', value: 'Paris' },
  { label: 'Tokyo', value: 'Tokyo' },
  { label: 'Beijing', value: 'Beijing' },
  { label: 'Mumbai', value: 'Mumbai' },
  { label: 'Rio de Janeiro', value: 'Rio de Janeiro' },
  { label: 'Moscow', value: 'Moscow' },
  { label: 'Johannesburg', value: 'Johannesburg' },
  { label: 'Mexico City', value: 'Mexico City' },
  { label: 'Buenos Aires', value: 'Buenos Aires' },
  { label: 'Rome', value: 'Rome' },
];

export const states = [
  { label: 'New York', value: 'New York' },
  { label: 'England', value: 'England' },
  { label: 'Ontario', value: 'Ontario' },
  { label: 'New South Wales', value: 'New South Wales' },
  { label: 'Berlin', value: 'Berlin' },
  { label: 'Île-de-France', value: 'Île-de-France' },
  { label: 'Tokyo', value: 'Tokyo' },
  { label: 'Beijing', value: 'Beijing' },
  { label: 'Maharashtra', value: 'Maharashtra' },
  { label: 'Rio de Janeiro', value: 'Rio de Janeiro' },
  { label: 'Moscow', value: 'Moscow' },
  { label: 'Gauteng', value: 'Gauteng' },
  { label: 'Mexico City', value: 'Mexico City' },
  { label: 'Buenos Aires', value: 'Buenos Aires' },
  { label: 'Lazio', value: 'Lazio' },
];

export const familyStatus = [
  { label: 'Middle Class', value: 'Middle Class' },
  { label: 'Upper Middle Class', value: 'Upper Middle Class' },
  { label: 'High Class', value: 'High Class' },
  { label: 'Rich/Affluent', value: 'Rich/Affluent' },
];

export const familyTypes = [
  { label: 'Joint', value: 'Joint' },
  { label: 'Nuclear', value: 'Nuclear' },
];

export const familyValues = [
  { label: 'Orthodox', value: 'Orthodox' },
  { label: 'Traditional', value: 'Traditional' },
  { label: 'Moderate', value: 'Moderate' },
  { label: 'Liberal', value: 'Liberal' },
];

export const languages = [
  { label: 'English', value: 'English' },
  { label: 'Spanish', value: 'Spanish' },
  { label: 'French', value: 'French' },
  { label: 'German', value: 'German' },
  { label: 'Chinese', value: 'Chinese' },
  { label: 'Japanese', value: 'Japanese' },
  { label: 'Hindi', value: 'Hindi' },
  { label: 'Portuguese', value: 'Portuguese' },
  { label: 'Russian', value: 'Russian' },
  { label: 'Italian', value: 'Italian' },
  { label: 'Arabic', value: 'Arabic' },
  { label: 'Dutch', value: 'Dutch' },
  { label: 'Korean', value: 'Korean' },
  { label: 'Turkish', value: 'Turkish' },
  { label: 'Swedish', value: 'Swedish' },
];

export const hobbies = [
  { label: 'Reading', value: 'Reading' },
  { label: 'Cooking', value: 'Cooking' },
  { label: 'Traveling', value: 'Traveling' },
  { label: 'Photography', value: 'Photography' },
  { label: 'Painting', value: 'Painting' },
  { label: 'Gardening', value: 'Gardening' },
  { label: 'Playing Musical Instruments', value: 'Playing Musical Instruments' },
  { label: 'Hiking', value: 'Hiking' },
  { label: 'Yoga', value: 'Yoga' },
  { label: 'Watching Movies', value: 'Watching Movies' },
  { label: 'Playing Video Games', value: 'Playing Video Games' },
  { label: 'Fishing', value: 'Fishing' },
  { label: 'Dancing', value: 'Dancing' },
  { label: 'Singing', value: 'Singing' },
  { label: 'DIY Crafts', value: 'DIY Crafts' },
  { label: 'Camping', value: 'Camping' },
  { label: 'Writing', value: 'Writing' },
  { label: 'Cycling', value: 'Cycling' },
  { label: 'Running', value: 'Running' },
  { label: 'Mediation', value: 'Mediation' },
];
