export const heights = [
  { label: '4.5', value: '4.5' },
  { label: '4.6', value: '4.6' },
  { label: '4.7', value: '4.7' },
  { label: '4.8', value: '4.8' },
  { label: '4.9', value: '4.9' },
  { label: '5.0', value: '5.0' },
  { label: '5.1', value: '5.1' },
  { label: '5.2', value: '5.2' },
  { label: '5.3', value: '5.3' },
  { label: '5.4', value: '5.4' },
  { label: '5.5', value: '5.5' },
  { label: '5.6', value: '5.6' },
  { label: '5.7', value: '5.7' },
  { label: '5.8', value: '5.8' },
  { label: '5.9', value: '5.9' },
  { label: '6.0', value: '6.0' },
  { label: '6.1', value: '6.1' },
  { label: '6.2', value: '6.2' },
  { label: '6.3', value: '6.3' },
  { label: '6.4', value: '6.4' },
  { label: '6.5', value: '6.5' },
  { label: '6.6', value: '6.6' },
  { label: '6.7', value: '6.7' },
  { label: '6.8', value: '6.8' },
  { label: '6.9', value: '6.9' },
  { label: '7.0', value: '7.0' },
];

export const weight = [
  { label: '40 kg', value: '40kg' },
  { label: '41 kg', value: '41kg' },
  { label: '42 kg', value: '42kg' },
  { label: '43 kg', value: '43kg' },
  { label: '44 kg', value: '44kg' },
  { label: '45 kg', value: '45kg' },
  { label: '46 kg', value: '46kg' },
  { label: '47 kg', value: '47kg' },
  { label: '48 kg', value: '48kg' },
  { label: '49 kg', value: '49kg' },
  { label: '50 kg', value: '50kg' },
  { label: '51 kg', value: '51kg' },
  { label: '52 kg', value: '52kg' },
  { label: '53 kg', value: '53kg' },
  { label: '54 kg', value: '54kg' },
  { label: '55 kg', value: '55kg' },
  { label: '56 kg', value: '56kg' },
  { label: '57 kg', value: '57kg' },
  { label: '58 kg', value: '58kg' },
  { label: '59 kg', value: '59kg' },
  { label: '60 kg', value: '60kg' },
  { label: '61 kg', value: '61kg' },
  { label: '62 kg', value: '62kg' },
  { label: '63 kg', value: '63kg' },
  { label: '64 kg', value: '64kg' },
  { label: '65 kg', value: '65kg' },
  { label: '66 kg', value: '66kg' },
  { label: '67 kg', value: '67kg' },
  { label: '68 kg', value: '68kg' },
  { label: '69 kg', value: '69kg' },
  { label: '70 kg', value: '70kg' },
  { label: '71 kg', value: '71kg' },
  { label: '72 kg', value: '72kg' },
  { label: '73 kg', value: '73kg' },
  { label: '74 kg', value: '74kg' },
  { label: '75 kg', value: '75kg' },
  { label: '76 kg', value: '76kg' },
  { label: '77 kg', value: '77kg' },
  { label: '78 kg', value: '78kg' },
  { label: '79 kg', value: '79kg' },
  { label: '80 kg', value: '80kg' },
  { label: '81 kg', value: '81kg' },
  { label: '82 kg', value: '82kg' },
  { label: '83 kg', value: '83kg' },
  { label: '84 kg', value: '84kg' },
  { label: '85 kg', value: '85kg' },
  { label: '86 kg', value: '86kg' },
  { label: '87 kg', value: '87kg' },
  { label: '88 kg', value: '88kg' },
  { label: '89 kg', value: '89kg' },
  { label: '90 kg', value: '90kg' },
  { label: '91 kg', value: '91kg' },
  { label: '92 kg', value: '92kg' },
  { label: '93 kg', value: '93kg' },
  { label: '94 kg', value: '94kg' },
  { label: '95 kg', value: '95kg' },
  { label: '96 kg', value: '96kg' },
  { label: '97 kg', value: '97kg' },
  { label: '98 kg', value: '98kg' },
  { label: '99 kg', value: '99kg' },
  { label: '100 kg', value: '100kg' },
  { label: '101 kg', value: '101kg' },
  { label: '102 kg', value: '102kg' },
  { label: '103 kg', value: '103kg' },
  { label: '104 kg', value: '104kg' },
  { label: '105 kg', value: '105kg' },
  { label: '106 kg', value: '106kg' },
  { label: '107 kg', value: '107kg' },
  { label: '108 kg', value: '108kg' },
  { label: '109 kg', value: '109kg' },
  { label: '110 kg', value: '110kg' },
  { label: '111 kg', value: '111kg' },
  { label: '112 kg', value: '112kg' },
  { label: '113 kg', value: '113kg' },
  { label: '114 kg', value: '114kg' },
  { label: '115 kg', value: '115kg' },
  { label: '116 kg', value: '116kg' },
  { label: '117 kg', value: '117kg' },
  { label: '118 kg', value: '118kg' },
  { label: '119 kg', value: '119kg' },
  { label: '120 kg', value: '120kg' },
  { label: '121 kg', value: '121kg' },
  { label: '122 kg', value: '122kg' },
  { label: '123 kg', value: '123kg' },
  { label: '124 kg', value: '124kg' },
  { label: '125 kg', value: '125kg' },
  { label: '126 kg', value: '126kg' },
  { label: '127 kg', value: '127kg' },
  { label: '128 kg', value: '128kg' },
  { label: '129 kg', value: '129kg' },
  { label: '130 kg', value: '130kg' },
  { label: '131 kg', value: '131kg' },
  { label: '132 kg', value: '132kg' },
  { label: '133 kg', value: '133kg' },
  { label: '134 kg', value: '134kg' },
  { label: '135 kg', value: '135kg' },
  { label: '136 kg', value: '136kg' },
  { label: '137 kg', value: '137kg' },
  { label: '138 kg', value: '138kg' },
  { label: '139 kg', value: '139kg' },
  { label: '140 kg', value: '140kg' },
];

export const age = [
  { label: '18', value: '18' },
  { label: '19', value: '19' },
  { label: '20', value: '20' },
  { label: '21', value: '21' },
  { label: '22', value: '22' },
  { label: '23', value: '23' },
  { label: '24', value: '24' },
  { label: '25', value: '25' },
  { label: '26', value: '26' },
  { label: '27', value: '27' },
  { label: '28', value: '28' },
  { label: '29', value: '29' },
  { label: '30', value: '30' },
  { label: '31', value: '31' },
  { label: '32', value: '32' },
  { label: '33', value: '33' },
  { label: '34', value: '34' },
  { label: '35', value: '35' },
  { label: '36', value: '36' },
  { label: '37', value: '37' },
  { label: '38', value: '38' },
  { label: '39', value: '39' },
  { label: '40', value: '40' },
];

export const bodyTypes = [
  { label: 'Slim', value: 'slim' },
  { label: 'Athletic', value: 'athletic' },
  { label: 'Average', value: 'average' },
  { label: 'Heavy', value: 'heavy' },
];

export const physicalStatus = [
  { label: 'Normal', value: 'normal' },
  { label: 'Physically challenged', value: 'physically_challenged' },
];

export const maritalStatus = [
  { label: 'Never married', value: 'normal' },
  { label: 'Widowed', value: 'widowed' },
  { label: 'Divorced', value: 'divorced' },
  { label: 'Awaiting divorce', value: 'awaiting_divorce' },
];

export const eatingHabits = [
  { label: 'Vegetarian', value: 'vegetarian' },
  { label: 'Non vegetarian', value: 'non_vegetarian' },
];

export const drinkingHabits = [
  { label: 'Never', value: 'never' },
  { label: 'Ocassionally', value: 'ocassionally' },
  { label: 'Regulary', value: 'regulary' },
];

export const smokingHabits = [
  { label: 'Never', value: 'never' },
  { label: 'Ocassionally', value: 'ocassionally' },
  { label: 'Regulary', value: 'regulary' },
];

export const religions = [
  { label: 'Hinduism', value: 'hinduism' },
  { label: 'Islam', value: 'islam' },
  { label: 'Christianity', value: 'christianity' },
  { label: 'Sikhism', value: 'sikhism' },
  { label: 'Buddhism', value: 'buddhism' },
  { label: 'Jainism', value: 'jainism' },
  { label: 'Zoroastrianism', value: 'zoroastrianism' },
  { label: 'Baháí Faith', value: 'bahai_faith' },
  { label: 'Tribal Religions', value: 'tribal_religions' },
  { label: 'Judaism', value: 'judaism' },
];

export const ethnicities = [
  { label: 'Bengali', value: 'bengali' },
  { label: 'Punjabi', value: 'punjabi' },
  { label: 'Gujarati', value: 'gujarati' },
  { label: 'Marathi', value: 'marathi' },
  { label: 'Tamil', value: 'tamil' },
  { label: 'Telugu', value: 'telugu' },
  { label: 'Kannada', value: 'kannada' },
  { label: 'Odia', value: 'odia' },
  { label: 'Assamese', value: 'assamese' },
  { label: 'Kashmiri', value: 'kashmiri' },
];

export const caste = [
  { label: 'Brahmins', value: 'brahmins' },
  { label: 'Kshatriyas', value: 'kshatriyas' },
  { label: 'Vaishyas', value: 'vaishyas' },
  { label: 'Shudras', value: 'shudras' },
  { label: 'Dalits', value: 'dalits' },
];

export const educationalQualifications = [
  { label: 'High School Diploma', value: 'high_school_diploma' },
  { label: "Bachelor's Degree", value: 'bachelors_degree' },
  { label: "Master's Degree", value: 'masters_degree' },
  { label: 'Doctorate (Ph.D.)', value: 'phd' },
  { label: "Associate's Degree", value: 'associates_degree' },
  { label: 'Professional Certification', value: 'professional_certification' },
  { label: 'Vocational Training', value: 'vocational_training' },
  { label: 'Postgraduate Diploma', value: 'postgraduate_diploma' },
  { label: 'Certificate Program', value: 'certificate_program' },
  { label: 'Technical Degree', value: 'technical_degree' },
];

export const employeeSectors = [
  { label: 'Information Technology', value: 'information_technology' },
  { label: 'Healthcare', value: 'healthcare' },
  { label: 'Finance', value: 'finance' },
  { label: 'Education', value: 'education' },
  { label: 'Manufacturing', value: 'manufacturing' },
];

export const occupations = [
  { label: 'Teacher', value: 'teacher' },
  { label: 'Doctor', value: 'doctor' },
  { label: 'Engineer', value: 'engineer' },
  { label: 'Accountant', value: 'accountant' },
  { label: 'Lawyer', value: 'lawyer' },
  { label: 'Chef', value: 'chef' },
  { label: 'Artist', value: 'artist' },
  { label: 'Police Officer', value: 'police_officer' },
  { label: 'Journalist', value: 'journalist' },
  { label: 'Salesperson', value: 'salesperson' },
  { label: 'Electrician', value: 'electrician' },
  { label: 'Plumber', value: 'plumber' },
];

export const annualIncomes = [
  { label: 'Less than $20,000', value: 'less_than_20000' },
  { label: '$20,000 - $40,000', value: '20000_to_40000' },
  { label: '$40,000 - $60,000', value: '40000_to_60000' },
  { label: '$60,000 - $80,000', value: '60000_to_80000' },
  { label: '$80,000 - $100,000', value: '80000_to_100000' },
  { label: 'More than $100,000', value: 'more_than_100000' },
];

export const countries = [
  { label: 'United States', value: 'united_states' },
  { label: 'United Kingdom', value: 'united_kingdom' },
  { label: 'Canada', value: 'canada' },
  { label: 'Australia', value: 'australia' },
  { label: 'Germany', value: 'germany' },
  { label: 'France', value: 'france' },
  { label: 'Japan', value: 'japan' },
  { label: 'China', value: 'china' },
  { label: 'India', value: 'india' },
  { label: 'Brazil', value: 'brazil' },
  { label: 'Russia', value: 'russia' },
  { label: 'South Africa', value: 'south_africa' },
  { label: 'Mexico', value: 'mexico' },
  { label: 'Argentina', value: 'argentina' },
  { label: 'Italy', value: 'italy' },
];

export const cities = [
  { label: 'New York', value: 'new_york' },
  { label: 'London', value: 'london' },
  { label: 'Toronto', value: 'toronto' },
  { label: 'Sydney', value: 'sydney' },
  { label: 'Berlin', value: 'berlin' },
  { label: 'Paris', value: 'paris' },
  { label: 'Tokyo', value: 'tokyo' },
  { label: 'Beijing', value: 'beijing' },
  { label: 'Mumbai', value: 'mumbai' },
  { label: 'Rio de Janeiro', value: 'rio_de_janeiro' },
  { label: 'Moscow', value: 'moscow' },
  { label: 'Johannesburg', value: 'johannesburg' },
  { label: 'Mexico City', value: 'mexico_city' },
  { label: 'Buenos Aires', value: 'buenos_aires' },
  { label: 'Rome', value: 'rome' },
];

export const states = [
  { label: 'New York', value: 'new_york' },
  { label: 'England', value: 'england' },
  { label: 'Ontario', value: 'ontario' },
  { label: 'New South Wales', value: 'new_south_wales' },
  { label: 'Berlin', value: 'berlin' },
  { label: 'Île-de-France', value: 'ile_de_france' },
  { label: 'Tokyo', value: 'tokyo' },
  { label: 'Beijing', value: 'beijing' },
  { label: 'Maharashtra', value: 'maharashtra' },
  { label: 'Rio de Janeiro', value: 'rio_de_janeiro' },
  { label: 'Moscow', value: 'moscow' },
  { label: 'Gauteng', value: 'gauteng' },
  { label: 'Mexico City', value: 'mexico_city' },
  { label: 'Buenos Aires', value: 'buenos_aires' },
  { label: 'Lazio', value: 'lazio' },
];
