
import { auth } from "@/auth";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Sofia, Sofia_Sans } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

const sofia_init = Sofia_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sofia_sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider session={session}>

        <body className={sofia_init.className}>
          <div className="">
            {/* <Navbar /> */}
            {children}
          </div>
          <Toaster />
        </body>
      </SessionProvider>
    </html>
  );
}
